# チェックされていない外部呼び出し (Unchecked External Calls)

### 説明
Ethereum では、コントラクトが別のコントラクトを呼び出すと、呼び出されたコントラクトは例外をスローせずに静かに失敗することがあります。呼び出し側のコントラクトが呼び出し結果をチェックしない場合、呼び出しが成功していなくても、成功したとみなす可能性があります。

### 影響
チェックされていない外部呼び出しはトランザクションの失敗、資金の損失、不正なコントラクト状態につながる可能性があります。

### 修正手順
1. `call`, `delegatecall`, `callcode` の返り値を常にチェックします。
2. 失敗すると自動的に元に戻るため、 `call.value()()` の代わりに Solidity の `transfer` または `send` 機能を使用します。

### 事例
コントラクトは `call` 機能を使用して Ether をあるアドレスに送信します。呼び出しが失敗した場合 (たとえば、受信者が支払い可能なフィードバック機能のないコントラクトの場合) 、送信側のコントラクトは転送が成功したと誤って想定する可能性があります。
